# Generated by Django 4.0.8 on 2023-02-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turf_name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('turf_image', models.ImageField(upload_to='static/image')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('turf_size', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
