# Generated by Django 4.0.8 on 2023-02-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booked_turf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked_turf',
            name='email',
        ),
    ]
