# Generated by Django 4.0.8 on 2023-02-22 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_booked_turf_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_turf',
            name='slot',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 20, 59, 38, 198086)),
        ),
    ]
