# Generated by Django 4.0.8 on 2023-03-21 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_booked_turf_time_alter_turf_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 16, 51, 42, 391292)),
        ),
        migrations.AlterField(
            model_name='turf',
            name='turf_image',
            field=models.ImageField(upload_to='media/turf_images'),
        ),
    ]
