# Generated by Django 4.0.8 on 2023-03-21 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_booked_turf_time_alter_turf_turf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 16, 55, 8, 648300)),
        ),
        migrations.AlterField(
            model_name='turf',
            name='turf_image',
            field=models.ImageField(upload_to='turf_images'),
        ),
    ]
