# Generated by Django 4.0.8 on 2023-03-21 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_booked_turf_time_alter_turf_turf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 17, 56, 11, 84160)),
        ),
    ]
