# Generated by Django 4.0.8 on 2023-03-22 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_booked_turf_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_turf',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 10, 35, 53, 213662)),
        ),
    ]
