# Generated by Django 4.0.8 on 2023-03-22 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_booked_turf_price_alter_booked_turf_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 10, 38, 47, 58485)),
        ),
        migrations.AlterField(
            model_name='turf',
            name='price',
            field=models.IntegerField(),
        ),
    ]
