# Generated by Django 4.0.8 on 2023-03-22 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_booked_turf_email_alter_booked_turf_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_turf',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 14, 53, 35, 88470)),
        ),
    ]
