# Generated by Django 4.0.8 on 2023-03-22 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_booked_turf_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 15, 47, 7, 612350)),
        ),
    ]
