# Generated by Django 4.0.8 on 2023-03-22 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_booked_turf_contact_alter_booked_turf_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 15, 58, 59, 565961)),
        ),
    ]
