# Generated by Django 4.0.8 on 2023-03-22 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_booked_turf_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 22, 21, 59, 11, 701994)),
        ),
        migrations.AlterField(
            model_name='turf',
            name='turf_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
