# Generated by Django 4.0.8 on 2023-03-24 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_booked_turf_time_alter_turf_turf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='user_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 24, 7, 14, 45, 297890)),
        ),
    ]
