# Generated by Django 4.0.8 on 2023-03-24 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_booked_turf_time_alter_users_manager_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 24, 20, 22, 36, 3139)),
        ),
        migrations.AlterField(
            model_name='users',
            name='manager_status',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
