# Generated by Django 4.0.8 on 2023-03-25 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_turf_booked_slot_1_turf_booked_slot_10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_1',
            new_name='slot_10_11',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_10',
            new_name='slot_11_12',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_11',
            new_name='slot_12_1',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_12',
            new_name='slot_1_2',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_13',
            new_name='slot_2_3',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_2',
            new_name='slot_3_4',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_3',
            new_name='slot_4_5',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_4',
            new_name='slot_5_6',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_5',
            new_name='slot_6_7',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_6',
            new_name='slot_7_8',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_7',
            new_name='slot_8_10',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_8',
            new_name='slot_8_9',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='booked_slot_9',
            new_name='slot_9_10',
        ),
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 14, 37, 32, 4301)),
        ),
    ]
