# Generated by Django 4.0.8 on 2023-03-25 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_booked_slot_1_turf_slot_10_11_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='slot_8_10',
            new_name='slot_9_10a',
        ),
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 25, 15, 2, 14, 180249)),
        ),
    ]
