# Generated by Django 4.0.8 on 2023-03-26 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_slot_8_10_turf_slot_9_10a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='end',
        ),
        migrations.RemoveField(
            model_name='turf',
            name='start',
        ),
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 26, 8, 30, 55, 87762)),
        ),
    ]
