# Generated by Django 4.0.8 on 2023-03-26 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_turf_end_remove_turf_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_turf',
            name='time',
            field=models.DateField(default=datetime.datetime(2023, 3, 26, 9, 0, 0, 797836)),
        ),
    ]
